### ISSUE TITLE
Comparison to Observable?

### ISSUE THREAD

**Issue by clayrat** [lihaoyi/geny#2]
I wonder how does this compare to `Observable`, as found e.g., in [Monix](https://monix.io/). It has been said that Observable is also a dual of Iterator, they also deal with resource clean-up, etc. Generators don't seem to deal with asynchrony though.

**Comment by pathikrit** [comment]
Perhaps not the best place to ask this but I was wondering the same. How does Generator compare to Enumerator/Iteratees? Any pointers to literature around this?

References: 
https://en.wikipedia.org/wiki/Iteratee
http://blog.higher-order.com/blog/2010/10/14/scalaz-tutorial-enumeration-based-io-with-iteratees/
https://wiki.haskell.org/Enumerator_and_iteratee

**Comment by lihaoyi** [comment]
Generator is 1 file with ~300 lines of code, including scaladoc explaining what it is. You can probably understand that 300 lines of code faster than trying to find some academic paper covering it, and make your own comparison to other abstractions you are familiar with.

**Comment by pathikrit** [comment]
Of ofcourse - I was not really talking about the implementation but _conceptually_ what's the difference between Enumerator (not the Java one) vs. Iteratee vs. Generator. Again apologies if this is not the right medium for such a discussion.

A high level understanding would be this is a generator (atleast in this library):
```scala
trait Generator[A] {
  def generate(a: A => Continue | End): Unit
  // Every other operation defined in terms of above
}
```

and this is an Iterator (conceptually):
```scala
trait Iterator[A] {
  def next(): Option[A]
}
```

This is a Iteratee:
```scala
sealed trait Iteratee[I, O]
case class Done[O](result: O) extends Iteratee[Nothing, O]
case class Next[I, O](next: I => Iterator[I, O]) extends Iteratee[I, O]
```

It can also be written without an ADT like:
```scala
trait Iteratee[I, O] {
  def next(item: I): O | Iteratee[I, O]
}
```

And, lastly this is an Enumerator (not to be confused with Java's enumerations):
```scala
trait Enumerator[I] {
  def apply[A](i: Iteratee[I, A]): Iteratee[I, A]
}
```

I believe it is possible to map Generator to an Enumerator (is it worth it is another question but purely for academic interest and at best, correct naming of things).

**Comment by lihaoyi** [comment]
That seems about right.

I never really managed to work my head around Enumerator/Iteratee, from back when Play used to used them in 2012, so you'll have to figure them out on your own.

As far as I know, `Generator` is closest to `scala.Traversable` in that it's defined around a `foreach` function, though without all the useless strict overrides traversable has, and with the option for early termination.

**Comment by pathikrit** [comment]
Ok found the literature I was looking for: 

http://okmij.org/ftp/Haskell/Iteratee/ vs 
http://okmij.org/ftp/continuations/generators.html

Correct me if I am wrong but it looks like:

1. `Iteratee` are the true "duals of Iterators". (makes sense since Iterators "produce" and Iteratees "consume")
2. Enumerators "handle Iteratees" i.e. for I/O, Enumerators would be responsible for doing cleanups rather than the Iteratee themselves (separation of concerns). Another possible way to grok Enumerators are that they can `fold` over Iteratees.
3. Generator as implemented in this library is close conceptually to what an `Iteratee` is rather than to the Generator discussed [here](http://okmij.org/ftp/continuations/generators.html). `Generator.SelfClosing` is perhaps closer to an Enumerator rather than an `Iteratee`.

If you were to ever reimplement this library, I would recommend renaming to Iteratee/Enumerator :)

**Comment by lihaoyi** [comment]
@pathikrit haha I have totally given up on the whole Iteratee/Enumerator/Enumeratee thing. I struggled with those guys sooooo much back when Play Framework had just reached 2.0, I have a visceral reaction to even hearing those words and never want to go back to them :D

Note that things like `Generator` or `Enumerator` means different things in literally every programming language. I personally don't care what Haskell uses the term for, because Python will use it differently, as will C#, Java, Javascript, and so on.

If that understanding works for you then great. For me, I'm happy with using `geny.Generator` all over the place without any deeper understanding...

**Comment by pathikrit** [comment]
I agree, the Play one is terrible (and they use Enumerator wrong - it returns a `Future`! which is terrible).
